# download mikrotik
setup:
	wget https://github.com/elseif/MikroTikPatch/releases/download/7.19.4/chr-7.19.4-legacy-bios.img.zip
	unzip chr-7.19.4-legacy-bios.img.zip
install:
	qm disk import 100 chr-7.19.4-legacy-bios.img local-lvm
