# login
login:
	cloudflared tunnel login
# need to login to have credential-files

# create tunnel
APP ?=
create:
	cloudflared tunnel create $(APP)

# get the UUID and then modify config.yaml

APP ?=
run:
	cloudflared tunnel run $(APP)

